config/routes.rb
DefaultSite::Application.routes.draw do
  scope 'admin' do
    resources :documents
    resources :images do
      collection { get :galleries }
    end
    resources :pages do
      resources :widgets
    end
    resources :nav_menus do
      resources :nav_items
    end
    resources :users do
      member do
        get :change_password
      end
    end
    match '/', :to => 'admin#home', :as => 'admin_home'

    post "/nav_menus/order_nav_items", :to => 'nav_menus#order_nav_items', :as => :order_nav_items
    post "/order_images", :to => 'images#order_images', :as => :order_images
    post '/order_widgets', :to => 'pages#order_widgets', :as => :order_widgets
  end
  
  resources :sessions, :only => [:create]

  match '/signin', :to => 'sessions#new', :as => :signin
  match '/signout', :to => 'sessions#destroy', :as => :signout
  
  post '/add_region', :to => 'pages#add_region', :as => :add_region
  
  # Routes in the host application
  get '/pages/:id', :to => 'pages#show', :as => :page_show
  match '/photos', :to => 'pages#show', :id => 'photos', :as => :photos
  match '/', :to => 'pages#show', :id => 'home', :as => :root
  
end

app/models/nav_item.rb
class NavItem
  include Mongoid::Document
  default_scope asc(:position)

  field :name
  field :link_target
  field :position
  field :link_type
  
  belongs_to :page 
  belongs_to :nav_menu
  
  before_create :set_position
  
  def set_position
    self.position = nav_menu.max_position + 1
  end
  
end

app/controllers/nav_items_controller.rb
class NavItemsController < AdminController

  def new
    @nav_menu = NavMenu.find(params[:nav_menu_id])
    @nav_item = @nav_menu.nav_items.new
  end

  def edit
    @nav_menu = NavMenu.find(params[:nav_menu_id])
    @nav_item = NavItem.find(params[:id])
  end

  def index
    @nav_menu = NavMenu.find(params[:nav_menu_id])    
  end

  def create
    nav_menu = NavMenu.find(params[:nav_menu_id])
    nav_item = nav_menu.nav_items.new(params[:nav_item])
    if nav_item.save
      redirect_to nav_menu_nav_items_path(nav_menu)
    else
      flash[:error] = "Nav Item could not be created"
      render :action => "new"
    end
  end

  def update
    nav_item = NavItem.find(params[:id])
    if nav_item.update_attributes(params[:nav_item])
      redirect_to nav_menu_nav_items_path(nav_item.nav_menu)
    else
      flash[:error] = "Nav Item could not be updated"      
      render :action => "edit"
    end
  end

  def destroy
    nav_item = NavItem.find(params[:id])
    nav_menu = nav_item.nav_menu
    nav_item.destroy
    redirect_to nav_menu_nav_items_path(nav_menu)
  end
end

app/views/nav_items/_form.html.erb
<%= form_for [@nav_menu, @nav_item] do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :link_target %>
    <%= f.text_field :link_target %>
  </div>
  <div class="button confirm_button">
    <%= f.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/nav_items/edit.html.erb
<div class="page_header">
	<h1>Editing nav_item</h1>
</div>

<section class="page_content">
	<%= render 'form' %>
</section>

app/views/nav_items/index.html.erb
<div class="top_right_controls">
	<%= link_to 'New Nav Item', new_nav_menu_nav_item_path(@nav_menu), :class => 'btn btn-info' %>
</div>

<div class="page_header">
	<h1><%= @nav_menu.name %> Links</h1>
</div>

<section class="page_content">
	<div class="field" id="sortable_nav_items">
		<% @nav_menu.nav_items.asc(:position).each do |nav_item| %>
			<div class="index_item" id="navitem_<%= nav_item.id %>">
				<div class="controls">
				  <%= link_to 'Delete', nav_menu_nav_item_path(@nav_menu, nav_item), :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger' %>
				  <%= link_to 'Edit', edit_nav_menu_nav_item_path(@nav_menu, nav_item), :class => 'btn btn-warning' %>			
				</div>
				<%= link_to nav_item.name, edit_nav_menu_nav_item_path(@nav_menu, nav_item) %>
			</div>
		<% end %>
	</div>
</section>

<%= javascript_tag do %>
  $('#sortable_nav_items').sortable(
  	{	axis: 'y', 
  		dropOnEmpty:false, 
     	items: '.index_item',
     	scroll: true,
      update: function(){
        $.ajax({
       	 type: 'post', 
         data: $('#sortable_nav_items').sortable('serialize') + '&id=<%= @nav_menu.id-%>',
         dataType: 'script', 
         url: '/admin/nav_menus/order_nav_items'
			  })
      }	
	})
<% end %>

app/views/nav_items/new.html.erb
<div class="page_header">
	<h1>New link</h1>
</div>

<section class="page_content">
	<%= render 'form' %>
</section>