config/routes.rb
DefaultSite::Application.routes.draw do
  scope 'admin' do
    resources :documents
    resources :images do
      collection { get :galleries }
    end
    resources :pages do
      resources :widgets
    end
    resources :nav_menus do
      resources :nav_items
    end
    resources :users do
      member do
        get :change_password
      end
    end
    match '/', :to => 'admin#home', :as => 'admin_home'

    post "/nav_menus/order_nav_items", :to => 'nav_menus#order_nav_items', :as => :order_nav_items
    post "/order_images", :to => 'images#order_images', :as => :order_images
    post '/order_widgets', :to => 'pages#order_widgets', :as => :order_widgets
  end
  
  resources :sessions, :only => [:create]

  match '/signin', :to => 'sessions#new', :as => :signin
  match '/signout', :to => 'sessions#destroy', :as => :signout
  
  post '/add_region', :to => 'pages#add_region', :as => :add_region
  
  # Routes in the host application
  get '/pages/:id', :to => 'pages#show', :as => :page_show
  match '/photos', :to => 'pages#show', :id => 'photos', :as => :photos
  match '/', :to => 'pages#show', :id => 'home', :as => :root
  
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, :type => String
  field :email, :type => String
  field :encrypted_password
  field :salt
  field :remember_token

  EmailRegex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/  
  
  attr_accessor :password, :confirm_password
  
  validates_format_of	:email, :with => EmailRegex
  validates_uniqueness_of :email, :case_sensitive => false
  validates_confirmation_of :password
  
  validates_presence_of :name, :on => :create
  validates_presence_of :password, :on => :create
  validates_length_of	:password, :within => 6..40, :on => :create
  
  before_save :encrypt_password
  
  def self.find_by_email(email)
    User.where(:email => email).first
  end

  def self.find_by_remember_token(remember_token)
    User.where(:remember_token => remember_token).first
  end
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = User.find_by_email(email)
     return nil if user.nil?
     return user if user.has_password?(submitted_password)
  end

  def remember_me!
    self.remember_token = encrypt("#{salt}--#{id}")
    save(:validate => false)
  end
  
  private
  
  def encrypt_password
    unless password.nil?
      self.salt = make_salt
      self.encrypted_password = encrypt(password)
    end
  end
  
  def encrypt(string) 
    secure_hash("#{salt}#{string}")
  end
  
  def make_salt
    secure_hash("#{Time.now.utc}#{password}")
  end
  
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end    
  
end

app/controllers/users_controller.rb
class UsersController < AdminController
  
  before_filter :login_required
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to(@user, :notice => 'User was successfully created.')
    else
      render :action => "new"
    end    
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to(@user, :notice => 'User was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(users_url)
  end
  
  def change_password
    @user = User.find(params[:id])    
  end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <% if @user.new_record? %>
		<div class="field">
	    <%= f.label :password %>
	    <%= f.password_field :password %>
	  </div>
		<div class="field">
	    <%= f.label :confirm_password %>
	    <%= f.password_field :confirm_password %>
	  </div>
	<% end %>
  <div class="button confirm_button">
    <%= f.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/users/change_password.html.erb
<h1>Change password</h1>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
	<div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="button confirm_button">
    <%= f.submit :class => 'btn btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="page_header">
	<h1>Editing user</h1>
</div>

<section class="page_content">
	<%= render 'form' %>
</section>

<%= link_to 'Change password', change_password_user_path(@user) %>

app/views/users/index.html.erb
<div class="top_right_controls">
	<%= link_to 'New User', new_user_path, :class => 'btn btn-info' %>
</div>

<div class="page_header">
	<h1>Users</h1>
</div>

<section class="page_content">
	<% @users.each do |user| %>
		<div class="index_item page_index_item">
			<div class="controls">
				<%= link_to 'Edit', edit_user_path(user), :class => 'btn btn-warning' %>
				<%= link_to 'Delete', user_path(user), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
			</div>
			<%= link_to user.name, edit_user_path(user) %>
		</div>
	<% end %>
</section>

app/views/users/new.html.erb
<div class="page_header">
	<h1>New user</h1>
</div>

<section class="page_content">
	<%= render 'form' %>
</section>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %>

app/views/users/signin.html.erb
<h1>Sign in</h1>
<div>
	<%= form_for(:user, :url => validate_users_path) do |f| %> 
		<div class="field">
			<%= f.label :email %><br />
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :password %><br /> 
			<%= f.password_field :password %>
		</div> 
		<div>
			<%= f.submit :class => 'btn btn-success' "Sign in" %> 
		</div>
		<% end %> 
</div>