config/routes.rb
DefaultSite::Application.routes.draw do
  scope 'admin' do
    resources :documents
    resources :images do
      collection { get :galleries }
    end
    resources :pages do
      resources :widgets
    end
    resources :nav_menus do
      resources :nav_items
    end
    resources :users do
      member do
        get :change_password
      end
    end
    match '/', :to => 'admin#home', :as => 'admin_home'

    post "/nav_menus/order_nav_items", :to => 'nav_menus#order_nav_items', :as => :order_nav_items
    post "/order_images", :to => 'images#order_images', :as => :order_images
    post '/order_widgets', :to => 'pages#order_widgets', :as => :order_widgets
  end
  
  resources :sessions, :only => [:create]

  match '/signin', :to => 'sessions#new', :as => :signin
  match '/signout', :to => 'sessions#destroy', :as => :signout
  
  post '/add_region', :to => 'pages#add_region', :as => :add_region
  
  # Routes in the host application
  get '/pages/:id', :to => 'pages#show', :as => :page_show
  match '/photos', :to => 'pages#show', :id => 'photos', :as => :photos
  match '/', :to => 'pages#show', :id => 'home', :as => :root
  
end

app/views/layouts/cms/_top_nav.html.erb
<div class="subnav">
	<div id="status">
		<% if current_user %>
			<%= current_user.name %> &nbsp; <%= link_to "Sign out", signout_path, :id => 'signout_link' %>
		<% else %>
			<%= link_to 'Sign in', signin_path %>						
		<% end %>
	</div>
	
	<ul class="nav nav-pills">
	  <li>
	    <a href="/admin/pages">Pages</a>
	  </li>
	
	  <li class="dropdown" id="menu1">
	    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
	      Images
	      <b class="caret"></b>
	    </a>
	    <ul class="dropdown-menu">
	    	<% Image::GALLERIES.each do |name, gallery| %>
	      	<li><%= link_to "#{gallery[:name]} Images", images_path(:gallery => gallery[:slug]) %></li>
	      <% end %>
	    </ul>
	  </li>

	  <li>
	    <a href="/admin/documents">Documents</a>
	  </li>
	
	  <li>
	    <a href="/admin/nav_menus">Links</a>
	  </li>

	  <li>
	    <a href="/admin/users">Users</a>
	  </li>
	
	</ul>	
</div>