config/routes.rb
DefaultSite::Application.routes.draw do
  scope 'admin' do
    resources :documents
    resources :images do
      collection { get :galleries }
    end
    resources :pages do
      resources :widgets
    end
    resources :nav_menus do
      resources :nav_items
    end
    resources :users do
      member do
        get :change_password
      end
    end
    match '/', :to => 'admin#home', :as => 'admin_home'

    post "/nav_menus/order_nav_items", :to => 'nav_menus#order_nav_items', :as => :order_nav_items
    post "/order_images", :to => 'images#order_images', :as => :order_images
    post '/order_widgets', :to => 'pages#order_widgets', :as => :order_widgets
  end
  
  resources :sessions, :only => [:create]

  match '/signin', :to => 'sessions#new', :as => :signin
  match '/signout', :to => 'sessions#destroy', :as => :signout
  
  post '/add_region', :to => 'pages#add_region', :as => :add_region
  
  # Routes in the host application
  get '/pages/:id', :to => 'pages#show', :as => :page_show
  match '/photos', :to => 'pages#show', :id => 'photos', :as => :photos
  match '/', :to => 'pages#show', :id => 'home', :as => :root
  
end

app/models/document.rb
class Document
  include Mongoid::Document

  field :name
  mount_uploader :file, DocumentUploader
  
end

app/controllers/documents_controller.rb
class DocumentsController < AdminController

  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
  end
  
  def create
    document = Document.new(params[:document])
    if document.save
  		redirect_to documents_path, :notice => "Successfully created document"
    else
      raise document.errors.inspect
      flash[:error] = "There was an error creating the document"
      redirect_to documents_path
    end
  end

  def edit
    @document = Document.find(params[:id])
  end

  def update
    document = Document.find(params[:id])
    if document.update_attributes(params[:document])
  		redirect_to documents_path, :notice => "Successfully updated document"
    else
      flash[:error] = "There was an error updating the document"
      render :action => 'edit'
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to documents_path
  end


end

app/views/documents/_form.html.erb
<%= form_for(@document, {:html => {:multipart => true}}) do |f| %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :document %>
		<%= f.file_field :file %>
	</div>  
	<div class="button confirm_button">
  	<%= f.submit :class => 'btn btn-success' %>
	</div>
<% end -%>

app/views/documents/edit.html.erb
<div class="page_header">
	<h1>Edit Document</h1>
</div>

<section class="page_content">
	<%= render 'form' %>
</section>

app/views/documents/index.html.erb
<div class="top_right_controls">
	<%= link_to 'New Document', new_document_path, :class => 'btn btn-info' %>
</div>

<div class="page_header">
	<h1>Documents</h1>
</div>

<section class="page_content">
	<div id="sortable_documents">
		<% @documents.each do |document| %>
			<div class="index_item document_index_item" id="document_<%= document.id %>">
				<div class="controls">
					<%= link_to 'Delete', document_path(document), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
					<%= link_to 'Edit', edit_document_path(document), :class => 'btn btn-warning' %>				
					<%= link_to 'View', view_document_path(document), :class => 'btn' %>									
				</div>
				<div class="documents_index_document">
					<%= document.name %>
				</div>
			</div>
		<% end %>
	</div>
</section>

app/views/documents/new.html.erb
<div class="page_header">
	<h1>New Document</h1>
</div>

<section class="page_content">
	<%= render 'form' %>
</section>